add service file setup
Consensys/doc.linea pull request #410
Opened 2024-01-30 08:24 UTC by Quilamir

Added a service file example for mainnet and testnet

2024-04-16 09:24 UTC, julien-marchand requested changes

2024-04-16 09:24 UTC, julien-marchand commented on docs/build-on-linea/run-a-node.mdx
> +Setup Linea as a Serivce
```suggestion
Setup Linea as a Service
```

2024-04-16 09:24 UTC, julien-marchand commented on docs/build-on-linea/run-a-node.mdx
> +--txpool.pricelimit 1000000000 \
```suggestion
--txpool.pricelimit 50000000 \
```

2024-04-16 09:24 UTC, julien-marchand commented on docs/build-on-linea/run-a-node.mdx
> +--txpool.pricelimit 1000000 \
```suggestion
--txpool.pricelimit 50000000 \
```

2024-12-20 20:53 UTC, MWGW commented on docs/build-on-linea/run-a-node.mdx
> +--txpool.pricelimit 1000000 \
> pricelimit

2025-01-07 13:17 UTC, jlwllmr commented
Closing due to inactivity.

2025-01-07 13:17 UTC, closed without merging