Move guides to community section
Consensys/doc.linea pull request #575
Opened 2024-05-22 10:25 UTC by lukecd

This pull request moves the Irys guides into the community section

2024-05-23 20:23 UTC, hadifalahi4142 commented
I think happen soon

2024-05-28 15:56 UTC, emilyJLin95 requested changes
https://github.com/Consensys/doc.linea/actions/runs/9272494953/job/25510411724?pr=575

You'll need to add words to `project-words.txt` and run `npm run lint` to make sure everything passes

2024-05-28 15:56 UTC, emilyJLin95 commented on sidebars.js
>        link: {
Was this all linter changes?

2024-06-06 00:15 UTC, bgravenorst commented
Closing in favour of https://github.com/Consensys/doc.linea/pull/594
Which duplicates this content and fixes cspell and includes edits for styling and readability.

2024-06-06 00:15 UTC, closed without merging