added ORA to oracles folder in docs
Consensys/doc.linea pull request #688
Opened 2024-08-15 16:45 UTC by Gwen-M

ORA OAO is deployed on Linea and available since a few months now, so here's a quickstart and few infos to help devs using OAO on Linea.

I tested it and it runs locally.

2024-08-16 08:50 UTC, jlwllmr requested changes
Thanks for putting this together -- just some minor changes needed.

2024-08-16 08:50 UTC, jlwllmr commented on docs/developers/tooling/oracles/ora.md
> +This quickstart is designed to help you to build a smart-contract on Linea able to interact with OAO. You can find more details in [our docs Quickstart](https://docs.ora.io/doc/oao-onchain-ai-oracle/
```suggestion
This quickstart is designed to help you to build a smart contract on Linea able to interact with OAO. You can find more details in [our docs Quickstart](https://docs.ora.io/doc/oao-onchain-ai-oracle/develop-guide).
```

2024-08-16 08:50 UTC, jlwllmr commented on docs/developers/tooling/oracles/ora.md
> +**2 models** are available on Linea: Stable Diffusion (ID: 50) and Llama3 8B Instruct (ID: 11).
```suggestion
**Two models** are available on Linea: Stable Diffusion (ID: 50) and Llama3 8B Instruct (ID: 11).
```

2024-08-16 08:50 UTC, jlwllmr commented on docs/developers/tooling/oracles/ora.md
> +For simpler application scenarios (eg. Prompt Engineering based AI like GPTs), you can directly use Prompt or SimplePrompt.
```suggestion
For simpler application scenarios (eg. Prompt Engineering-based AI like GPTs), you can directly use Prompt or SimplePrompt.
```

2024-08-16 10:36 UTC, Gwen-M commented
I've made the suggested changes, thanks :)

2024-08-19 14:02 UTC, jlwllmr approved these changes

2024-08-19 14:24 UTC, merged