Update Irys docs to use the latest version of Irys's tooling
Consensys/doc.linea pull request #738
Opened 2024-09-13 14:00 UTC by lukecd

This PR updates all Irys docs to use the latest version of our tooling.

2024-09-17 16:17 UTC, jlwllmr requested changes
Some minor changes — thank you for proactively updating this!

2024-09-17 16:17 UTC, jlwllmr commented on docs/developers/tooling/permanent-data/irys/irys-querying.mdx
I presume this is a renamed version of what was formerly `irys-query-package.mdx`? It's not essential, but if you think that page may be linked to elsewhere, it could be worth adding a redirect to `docusaurus.config.js`.

2024-09-17 16:17 UTC, jlwllmr commented on docs/developers/tooling/permanent-data/irys/irys-quickstart.mdx
> +Irys makes it easy to store your data onchain by supporting payments with ETH on Linea. With a single upfront payment, you can upload data, with guaranteed retrieval for a duration you set at the upl
```suggestion
Irys makes it easy to store your data onchain by supporting payments with ETH on Linea. With a single upfront payment, you can upload data, with guaranteed retrieval for a duration you set at the upload time — from a few days to forever.
```

2024-09-17 16:17 UTC, jlwllmr commented on docs/developers/tooling/permanent-data/irys/irys-quickstart.mdx
> +Using ETH on Linea
```suggestion
Using ETH on Linea:
```

2024-09-17 16:17 UTC, jlwllmr commented on docs/developers/tooling/permanent-data/irys/irys-quickstart.mdx
> +or the Irys devnet using ETH Sepolia on Linea
```suggestion
Or use the Irys devnet with Linea Sepolia ETH:
```

2024-09-24 08:49 UTC, lukecd commented on docs/developers/tooling/permanent-data/irys/irys-querying.mdx
Good idea! Added.

2024-10-07 10:06 UTC, jlwllmr approved these changes

2024-10-07 10:06 UTC, merged