Updating The Graph
Consensys/doc.linea pull request #892
Opened 2024-12-10 01:13 UTC by idalithb

Hi Linea! This includes updated docs for The Graph with a how-to guide for setting up a subgraph as quickly as possible.

2024-12-11 13:38 UTC, jlwllmr requested changes
This look great, thank you for the high-quality submission! 

Just a few pedantic suggestions to implement sentence case for headings.

2024-12-11 13:38 UTC, jlwllmr commented on docs/get-started/tooling/data-indexers/thegraph.mdx
> +## Quick Start
```suggestion
## Quickstart
```

2024-12-11 13:38 UTC, jlwllmr commented on docs/get-started/tooling/data-indexers/thegraph.mdx
> +## 1. Initialize Your Subgraph
```suggestion
## 1. Initialize your subgraph
```

2024-12-11 13:38 UTC, jlwllmr commented on docs/get-started/tooling/data-indexers/thegraph.mdx
> +### Create a Subgraph in Subgraph Studio
```suggestion
### Create a subgraph in subgraph studio
```

2024-12-11 13:38 UTC, jlwllmr commented on docs/get-started/tooling/data-indexers/thegraph.mdx
> +### Initialize Your Subgraph⁠
```suggestion
### Initialize your subgraph⁠
```

2024-12-11 13:38 UTC, jlwllmr commented on docs/get-started/tooling/data-indexers/thegraph.mdx
> +## 2. Deploy & Publish
```suggestion
## 2. Deploy and publish
```

2024-12-11 13:38 UTC, jlwllmr commented on docs/get-started/tooling/data-indexers/thegraph.mdx
> +### Test Your Subgraph
```suggestion
### Test your subgraph
```

2024-12-11 13:38 UTC, jlwllmr commented on docs/get-started/tooling/data-indexers/thegraph.mdx
> +### Publish Your Subgraph to The Graph's Decentralized Network
```suggestion
### Publish your subgraph to The Graph's decentralized network
```

2024-12-11 20:31 UTC, idalithb commented
@jlwllmr Thank you so much for the feedback! Please let me know if anything else is needed to have this merged 😄

2024-12-12 11:44 UTC, jlwllmr commented
@idalithb thanks! some of my suggestions haven't been committed yet, could you address those please?

2024-12-13 18:29 UTC, idalithb commented
> @idalithb thanks! some of my suggestions haven't been committed yet, could you address those please?

Done ✅

2024-12-16 14:35 UTC, jlwllmr approved these changes
LGTM!

2024-12-16 14:39 UTC, merged