Update doc: Reown and Primus Branding Integration
Consensys/doc.linea pull request #895
Opened 2024-12-11 14:10 UTC by qvkare

This update incorporates changes to reflect the recent rebranding and new integrations for both "Reown" and "Primus" protocols in the documentation.

### Changes Summary:

1. **Title Updates:**
   - Changed the title from "WalletConnect" to "Reown."
   - Added references to "Primus" where relevant to reflect the inclusion of its functionality.

2. **Image Updates:**
   - Updated image paths to reflect new branding:
     - `walletconnect.jpg` updated to `reown.jpg`.
     - Added `primus.jpg` for pages that introduce or highlight Primus functionalities.

3. **Text Updates:**
   - Replaced all instances of "WalletConnect" with "Reown."
   - Added "Primus" alongside relevant mentions of Reown to showcase its role in cryptographic attestations and privacy-preserving computations.
   - Updated links to the new [Reown Cloud](https://cloud.reown.com), the official [Reown website](https://reown.com), and [Primus Labs](https://www.primuslabs.xyz).

4. **Content Additions:**
   - Included descriptions of Primus's advanced cryptographic solutions (zkTLS and zkFHE) in relevant sections.
   - Highlighted the collaboration between Reown and Primus in enabling secure, privacy-preserving, and decentralized integrations.

5. **Consistency Improvements:**
   - Ensured all links and mentions align with the respective new brands.
   - Verified that references to "Primus" and "Reown" use updated terminology and maintain clarity across the documentation.

### Key Updated Links:
- [Reown Cloud](https://cloud.reown.com)
- [Reown Official Website](https://reown.com)
- [Primus Labs](https://www.primuslabs.xyz)

This update aligns the documentation with both Reown’s and Primus’s latest branding efforts, ensuring a cohesive and modern representation of the protocols.

2024-12-12 10:30 UTC, jlwllmr requested changes
A few things to adjust. Also seeing if I can push up the necessary changes to the redirects as it's hard to make the suggestion on the PR

2024-12-12 10:30 UTC, jlwllmr commented on docs/get-started/tooling/attestations/primus.mdx
I don't think we need to capitalise Primus everywhere — see their site: https://www.primuslabs.xyz/

The correct name seems to be `Primus`

2024-12-12 10:30 UTC, jlwllmr commented on docs/get-started/tooling/attestations/primus.mdx
> +PRIMUS is deployed on Linea and integrated with [Verax](https://github.com/Consensys/verax-documentation)
```suggestion
PRIMUS is deployed on Linea and integrated with [Verax](https://github.com/Consensys/verax-documentation),
```

2024-12-12 10:30 UTC, jlwllmr commented on docs/get-started/tooling/attestations/primus.mdx
> +- [Product tutorial](https://docs.primuslabs.xyz/)
```suggestion
- [Documentation](https://docs.primuslabs.xyz/)
```

2024-12-12 10:30 UTC, jlwllmr commented on docs/get-started/tooling/attestations/primus.mdx
> +- [Discord](https://discord.gg/YxJftNRxhh)
I think we need to remove this — the link is invalid and I can't see a Discord link on their site

2024-12-12 10:30 UTC, jlwllmr commented on docs/get-started/tooling/libraries/reown.mdx
> +title: REOWN Protocol
```suggestion
title: Reown
```

See their site — `Reown` isn't in caps: https://reown.com/

2024-12-12 10:30 UTC, jlwllmr commented on docs/get-started/tooling/libraries/reown.mdx
> +The REOWN protocol enables users from a multitude of wallets to log into decentralized applications. Linea is now listed inside the chain list for any project configuration on [REOWN Cloud](https://c
```suggestion
The Reown protocol enables users from a multitude of wallets to log into decentralized applications. Linea is now listed inside the chain list for any project configuration on [Reown Cloud](https://cloud.reown.com).
```

2024-12-12 10:30 UTC, jlwllmr commented on docs/get-started/tooling/libraries/reown.mdx
> +To learn more about the REOWN protocol, take a look at the official [page](https://reown.com/).
```suggestion
To learn more about the Reown protocol, take a look at the official [page](https://reown.com/).
```

2024-12-12 10:30 UTC, jlwllmr commented on redirects.json
> +        "from": "/developers/tooling/libraries/reown"
The redirects need to account for the old path, not the new one with `reown`. I'll see if I can push up a change to correct this.

2024-12-12 11:02 UTC, qvkare commented
I think we should add "Reown" to Vale's dictionary since it's causing spelling check errors in CI - I initially tried to work around this by adding "Protocol" suffix which wasn't the right approach.

2024-12-12 11:45 UTC, jlwllmr commented
@qvkare I'll add it to my list to submit to the central GH action that Vale runs from — I tend to do this in batches. But we can merge even though it's flagging it as an error. It doesn't influence the build

2024-12-12 11:46 UTC, jlwllmr commented on docs/get-started/tooling/attestations/primus.mdx
Could you address this please?

2024-12-12 12:04 UTC, qvkare reviewed
fix Documentation

2024-12-12 12:19 UTC, jlwllmr commented on docs/get-started/tooling/attestations/primus.mdx
> +- [Discord](https://discord.gg/YxJftNRxhh)
@qvkare does that link work for you? still invalid for me

2024-12-16 14:33 UTC, jlwllmr commented
@qvkare the state of the branch seems to have been reverted to its state before I last reviewed -- i.e. both protocols are still incorrectly capitalised in their respective files. Could you take a look at this please? 

I suspect some of the problems might stem from using the `update-node-size-data` branch.

2024-12-16 14:56 UTC, closed without merging