fix: typos
Consensys/doc.linea pull request #917
Opened 2024-12-28 20:01 UTC by destinyae

Fix typos

2025-01-06 16:40 UTC, jlwllmr commented on docs/release-notes.mdx
> +  Linea averaged ~150 transactions per batch; afterwards, it averaged ~1,500.
I don't think this is an error, since the `~1,500` is meant to reference the present. Maybe the wording would feel more natural if it were: 

> now, it averages ~1,500

2025-01-06 16:41 UTC, jlwllmr requested changes
Just one comment to resolve, the other changes look good to me.

2025-01-06 22:41 UTC, destinyae commented on docs/release-notes.mdx
> +  Linea averaged ~150 transactions per batch; afterwards, it averaged ~1,500.
ok : )

2025-01-07 11:44 UTC, jlwllmr approved these changes

2025-01-07 11:44 UTC, merged